[package]
name = "fib"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false

[dependencies]
